### ISSUE TITLE
Bytes vs bits

### ISSUE THREAD

**Issue by tobi-nmx** [akpw/mktxp#62]
I was wondering why the interface traffic seems to be so low. It looks like we are poling bytes (e.g. mktxp_interface_rx_byte_total) and displaying these als Mbits/s. I suggest changing the query to rate(mktxp_interface_rx_byte_total{routerboard_name="$node"}[1m])*8. Then the graphs look similar to Mikrotik's graphs (but much better, obviously).

**Comment by akpw** [comment]
looks like the `std unit` issue in the dashboard, the interface traffic panel indeed currently has `bit/sec` rather than `bytes/sec`. Changing the std unit to the latter should be fixing it: 

<img width="2301" alt="Screenshot 2023-01-10 at 14 12 03" src="https://user-images.githubusercontent.com/5028474/211560692-521a72e5-8070-445c-a034-bea87d897025.png">

I can change in the default dashboard, thanks for catching

**Comment by tobi-nmx** [comment]
That's a much more elegant solution. Thanks for the quick response!

**Comment by akpw** [comment]
> mega-bit is more common when it comes to bandwidth

a fair point, so I updated all traffic rates in the [default dashboard](https://grafana.com/grafana/dashboards/13679-mikrotik-mktxp-exporter/) accordingly. 

Moving fwd probably makes sense to export those in bits along with bytes, but for now should be a good enough workaround.
