### ISSUE TITLE
Constantly pinging speedtest/bandwidth related websites

### ISSUE THREAD

**Issue by johnmmcgee** [akpw/mktxp#72]
I am looking over my DNS logs and it appears that mktxp is constantly reaching out to speed benchmark related websites.  Is there a way to tune this setting?

Thank you

**Comment by jktjkt** [comment]
I, too, was surprised by this feature, and patched it out locally. Since I'm running my exporter in a public cloud outside of our network, this collector would just (potentially) add to my costs, and it surely provides no benefit for my use case. But anyway, of course I'm just a random user and whatever floats your boat, go for it, etc -- just sharing my feedback here. Thanks for a useful software.

I would go as far as to suggest moving this functionality to an external project because frankly, it seems like a strange piece of functionality in a "Prometheus Exporter for Mikrotik RouterOS devices". This is shown in the code which requires some special handling in the collector registry. Also, there also appears to be quite a few standalone projects for this ([1](https://brendonmatheson.com/2021/11/28/librespeed-prometheus-exporter.html), [2](https://github.com/nlamirault/speedtest_exporter), [3](https://github.com/jeanralphaviles/prometheus_speedtest),...).

**Comment by akpw** [comment]
@jktjkt a fair comment, this functionality was indeed mostly meant for my internal network env (as most of the package, initially). With mktxp getting some wider usage it does make sense to make this feature disabled by default, which hopefully should address the concern.
